//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterventionalCostings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class mySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static mySettings defaultInstance = ((mySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new mySettings())));
        
        public static mySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("someone@nhs.net")]
        public string OrdererEmail {
            get {
                return ((string)(this["OrdererEmail"]));
            }
            set {
                this["OrdererEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SEND.NHS.NET")]
        public string SmtpServerAddress {
            get {
                return ((string)(this["SmtpServerAddress"]));
            }
            set {
                this["SmtpServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SmtpServerPortNumber {
            get {
                return ((int)(this["SmtpServerPortNumber"]));
            }
            set {
                this["SmtpServerPortNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IMAP.NHS.NET")]
        public string ImapServerAddress {
            get {
                return ((string)(this["ImapServerAddress"]));
            }
            set {
                this["ImapServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("993")]
        public int ImapServerPortNumber {
            get {
                return ((int)(this["ImapServerPortNumber"]));
            }
            set {
                this["ImapServerPortNumber"] = value;
            }
        }
    }
}
